### ISSUE TITLE
Full export/import does not maintain subdirectory structure

### ISSUE THREAD

**Issue by galvornman** [spetzel2020/easy-exports#7]
Hello - 

Thanks for the nice back-up tool.  Was wondering if it was possible to preserve subdirectory structure when exporting/importing?  

For example, if items are organized into subdirectories in one world - when I export all the items I'd like for the subdirectories to be maintained when I import them into a new world.

**Comment by spetzel2020** [comment]
Good idea! I'll take a look.

**Comment by spetzel2020** [comment]
Unfortunately, there are a few roadblocks to being able to do this even in the simplest form of re-importing into the same world:

1. Current versions of Easy Export do not store the folder in the JSON export - I have changed this in my working version
2. When I re-import a JSON file into a temporary Compendium, Foundry throws away the folder information. I would need to write a custom re-importer 
3. At best, this would only work if the old folder existed already - otherwise I will need to export the Folder list as well and then re-create folders, especially if you're trying to move stuff to another world

Although all of the above is doable, unfortunately a larger scope than I can take on right now.

You may want to look at the Adventure import/export module which I think provides much of the above.

**Comment by galvornman** [comment]
Thanks for looking into this - I'll look at the Adventure import/export module as you suggest.
